import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ja' | 'en' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  ja: {
    'app.title': '仕事一覧',
    'tabs.jobs': 'お仕事',
    'tabs.refused': '見送り',
    'tabs.chosen': '応募済み',
    'tabs.profile': 'プロフィール',
    'contact.title': 'お問い合わせ',
    'contact.phone': '電話',
    'contact.email': 'メール',
    'contact.chat': 'チャット',
    'contact.subtitle': 'サポートチームにお気軽にお問い合わせください',
    'contact.phoneDetail': '月-金 9:00-18:00',
    'contact.emailDetail': '24時間以内に返信',
    'contact.chatDetail': '24時間対応',
    'profile.incomplete': 'プロフィールが未完成です',
    'profile.complete': 'プロフィールを完成させる',
    'profile.edit': 'プロフィール編集',
    'profile.basicInfo': '基本情報',
    'profile.contactInfo': '連絡先情報',
    'profile.workPreferences': '勤務希望',
    'profile.firstName': '名前',
    'profile.lastName': '苗字',
    'profile.age': '年齢',
    'profile.gender': '性別',
    'profile.nationality': '国籍',
    'profile.email': 'メールアドレス',
    'profile.phone': '電話番号',
    'profile.japaneseLevel': '日本語レベル',
    'profile.preferredDays': '希望勤務日',
    'profile.preferredJobTypes': '希望職種',
    'profile.addPhoto': '写真を追加',
    'profile.save': 'プロフィールを保存',
    'profile.male': '男性',
    'profile.female': '女性',
    'profile.other': 'その他',
    'profile.nearestStationInfo': '最寄り駅情報',
    'profile.nearestStationHome': '自宅最寄り駅',
    'profile.nearestStationSchool': '学校最寄り駅',
    'profile.walkTime': '徒歩時間（分）',
    'profile.addressInfo': '住所情報',
    'profile.postalCode': '郵便番号（7桁）',
    'profile.prefecture': '都道府県',
    'profile.district1': '市区町村1',
    'profile.district2': '市区町村2',
    'profile.buildingName': '建物名・部屋番号',
    'profile.residenceRights': '在留資格',
    'profile.visaType': 'ビザの種類',
    'profile.residencePhoto': '在留カード写真',
    'profile.residenceChangePlans': '在留資格変更予定',
    'profile.certificatePhoto': '証明書写真',
    'profile.otherInfo': 'その他の情報',
    'profile.currentJob': '現在の職業・学生',
    'profile.desiredJob': '希望する職種',
    'profile.workExperience': '過去の仕事・アルバイト経験',
    'profile.selectNationality': '国籍を選択',
    'profile.selectPrefecture': '都道府県を選択',
    'profile.selectVisaType': 'ビザの種類を選択',
    'profile.uploadResidenceCard': '在留カード写真をアップロード',
    'profile.uploadCertificate': '証明書写真をアップロード',
    'filter.title': 'フィルター',
    'filter.jobType': '職種',
    'filter.wage': '時給',
    'filter.japanese': '日本語レベル',
    'filter.workDays': '勤務日',
    'filter.commute': '通勤時間',
    'filter.workPriority': '仕事で大事な事',
    'filter.reset': 'リセット',
    'filter.apply': 'フィルターを適用',
    'sort.wage': '時給順',
    'sort.commute': '通勤時間順',
    'sort.date': '投稿日順',
    'sort.title': '並び替え',
    'empty.chosen': 'まだ応募した求人がありません',
    'empty.chosenSub': 'いいねした求人がここに表示されます',
    'empty.refused': 'まだ見送った求人がありません',
    'empty.refusedSub': 'パスした求人がここに表示されます',
    'language.select': '言語を選択',
    'settings.title': '設定',
    'settings.account': 'アカウント',
    'settings.editProfile': 'プロフィール編集',
    'settings.addAccount': 'アカウント追加',
    'settings.deleteAccount': 'アカウント削除',
    'settings.deleteAccountConfirm': '本当にアカウントを削除しますか？この操作は元に戻せません。',
    'settings.cancel': 'キャンセル',
    'settings.delete': '削除',
    'settings.preferences': '設定',
    'settings.support': 'サポート',
    'settings.contact': 'お問い合わせ',
    'settings.about': 'アプリについて',
    'settings.signOut': 'サインアウト',
    'settings.darkMode': 'ダークモード',
    'settings.notifications': '通知',
    
    // Job Detail Modal
    'modal.salary.title': '給与',
    'modal.salary.basic': '基本給与',
    'modal.salary.payment': '支払い方法',
    'modal.salary.description': '時給制。経験・能力に応じて昇給あり。',
    'modal.salary.monthlyPayment': '月末締め翌月25日払い',
    'modal.salary.bankTransfer': '銀行振込',
    'modal.salary.transportAllowance': '交通費別途支給',
    'modal.salary.raiseSystem': '昇給制度あり',
    'modal.salary.overtimePay': '残業手当あり',
    
    'modal.japanese.title': '日本語',
    'modal.japanese.recommended': '推奨日本語レベル',
    'modal.japanese.description': '企業が求める日本語レベルの目安',
    'modal.japanese.skills': '必要なスキル',
    'modal.japanese.dailyConversation': '基本的な日常会話',
    'modal.japanese.workInstructions': '業務指示の理解',
    'modal.japanese.reporting': '簡単な報告・連絡',
    'modal.japanese.keigo': '敬語の基本',
    'modal.japanese.numbers': '数字・時間の表現',
    
    'modal.commute.title': '通勤',
    'modal.commute.description': '自宅・学校から職場までの通勤時間目安。各種通勤オプションあり。',
    'modal.commute.options': '通勤オプション',
    'modal.commute.shuttleBus': '送迎バスあり',
    'modal.commute.bikePark': '駐輪場あり',
    'modal.commute.busNearby': 'バス停近く',
    'modal.commute.trainAccess': '電車アクセス良好',
    'modal.commute.parking': '駐車場完備',
    
    'modal.location.title': '場所',
    'modal.location.details': '勤務地詳細',
    'modal.location.access': 'アクセス情報',
    'modal.location.walkFromStation': '最寄り駅から徒歩5分',
    'modal.location.parkingAvailable': '駐車場完備',
    'modal.location.mainRoad': '主要道路沿い',
    'modal.location.busStop': 'バス停目の前',
    'modal.location.surroundings': '周辺環境',
    'modal.location.convenience': 'コンビニ近く',
    'modal.location.restaurants': '飲食店多数',
    'modal.location.atm': '銀行ATMあり',
    'modal.location.hospital': '病院・薬局近く',
    
    'modal.workDays.title': '勤務日',
    'modal.workDays.schedule': 'その店が募集する労働時間',
    'modal.workDays.shift1': '労働時間①',
    'modal.workDays.weekdays': '月　火　水　木　金',
    'modal.workDays.description': 'シフト制。相談に応じて調整可能。',
    
    'modal.workHours.title': '勤務時間',
    'modal.workHours.schedule': 'その店が募集する労働時間',
    'modal.workHours.shift1': '労働時間①',
    'modal.workHours.weekdays': '月　火　水　木　金',
    'modal.workHours.time': '05:00 ～ 08:00',
    'modal.workHours.description': '早朝勤務。体力に自信のある方歓迎。',
    'modal.workHours.break': '休憩時間',
    'modal.workHours.break30': '30分の休憩あり',
    'modal.workHours.breakRoom': '休憩室完備',
    'modal.workHours.freeDrink': '無料ドリンク',
    'modal.workHours.wifi': 'WiFi利用可能',
    
    'modal.highlights.title': '特典',
    'modal.highlights.appeal': 'アピールしたい職場の魅力',
    'modal.highlights.description': '企業からのアピールポイント',
    'modal.highlights.noExperience': '未経験OK',
    'modal.highlights.other': 'その他の特典',
    'modal.highlights.insurance': '社会保険完備',
    'modal.highlights.raise': '昇給あり',
    'modal.highlights.uniform': '制服貸与',
    'modal.highlights.training': '研修制度充実',
    'modal.highlights.discount': '社員割引あり',
    
    'modal.jobContent.title': '仕事内容',
    'modal.jobContent.description': '具体的な職務内容と求める人材',
    'modal.jobContent.mainTasks': '主な業務',
    'modal.jobContent.teamwork': 'チームワークを重視した作業',
    'modal.jobContent.safety': '安全管理の徹底',
    'modal.jobContent.quality': '品質管理・確認作業',
    'modal.jobContent.reporting': '報告書作成',
    'modal.jobContent.requirements': '求める人材',
    'modal.jobContent.motivated': 'やる気のある方',
    'modal.jobContent.teamPlayer': 'チームワークを大切にする方',
    'modal.jobContent.responsible': '責任感のある方',
    'modal.jobContent.learner': '学習意欲の高い方',
    'modal.jobContent.longTerm': '継続して働ける方',
  },
  en: {
    'app.title': 'Job List',
    'tabs.jobs': 'Jobs',
    'tabs.refused': 'Refused',
    'tabs.chosen': 'Chosen',
    'tabs.profile': 'Profile',
    'contact.title': 'Contact Us',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.chat': 'Live Chat',
    'contact.subtitle': 'Need help? Get in touch with our support team.',
    'contact.phoneDetail': 'Mon-Fri 9:00-18:00',
    'contact.emailDetail': 'Response within 24 hours',
    'contact.chatDetail': 'Available 24/7',
    'profile.incomplete': 'Profile is incomplete',
    'profile.complete': 'Complete Profile',
    'profile.edit': 'Edit Profile',
    'profile.basicInfo': 'Basic Information',
    'profile.contactInfo': 'Contact Information',
    'profile.workPreferences': 'Work Preferences',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.age': 'Age',
    'profile.gender': 'Gender',
    'profile.nationality': 'Nationality',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.japaneseLevel': 'Japanese Level',
    'profile.preferredDays': 'Preferred Work Days',
    'profile.preferredJobTypes': 'Preferred Job Types',
    'profile.addPhoto': 'Add Photo',
    'profile.save': 'Save Profile',
    'profile.male': 'Male',
    'profile.female': 'Female',
    'profile.other': 'Other',
    'profile.nearestStationInfo': 'Nearest Station Information',
    'profile.nearestStationHome': 'Nearest Station (Home)',
    'profile.nearestStationSchool': 'Nearest Station (School)',
    'profile.walkTime': 'Walk Time (minutes)',
    'profile.addressInfo': 'Address Information',
    'profile.postalCode': 'Postal Code (7 digits)',
    'profile.prefecture': 'Prefecture',
    'profile.district1': 'City/District 1',
    'profile.district2': 'City/District 2',
    'profile.buildingName': 'Building Name & Room Number',
    'profile.residenceRights': 'Residence Rights',
    'profile.visaType': 'Visa Type',
    'profile.residencePhoto': 'Residence Card Photo',
    'profile.residenceChangePlans': 'Residence Status Change Plans',
    'profile.certificatePhoto': 'Certificate Photo',
    'profile.otherInfo': 'Other Information',
    'profile.currentJob': 'Current Job/Student Status',
    'profile.desiredJob': 'Desired Job Type',
    'profile.workExperience': 'Past Work/Part-time Experience',
    'profile.selectNationality': 'Select Nationality',
    'profile.selectPrefecture': 'Select Prefecture',
    'profile.selectVisaType': 'Select Visa Type',
    'profile.uploadResidenceCard': 'Upload Residence Card Photo',
    'profile.uploadCertificate': 'Upload Certificate Photo',
    'filter.title': 'Filter',
    'filter.jobType': 'Job Type',
    'filter.wage': 'Wage',
    'filter.japanese': 'Japanese Level',
    'filter.workDays': 'Work Days',
    'filter.commute': 'Commute Time',
    'filter.workPriority': 'Work Priorities',
    'filter.reset': 'Reset',
    'filter.apply': 'Apply Filters',
    'sort.wage': 'By Wage',
    'sort.commute': 'By Commute',
    'sort.date': 'By Date',
    'sort.title': 'Sort By',
    'empty.chosen': 'No chosen jobs yet',
    'empty.chosenSub': 'Jobs you like will appear here',
    'empty.refused': 'No refused jobs yet',
    'empty.refusedSub': 'Jobs you pass on will appear here',
    'language.select': 'Select Language',
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.editProfile': 'Edit Profile',
    'settings.addAccount': 'Add Account',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountConfirm': 'Are you sure you want to delete your account? This action cannot be undone.',
    'settings.cancel': 'Cancel',
    'settings.delete': 'Delete',
    'settings.preferences': 'Preferences',
    'settings.support': 'Support',
    'settings.contact': 'Contact Us',
    'settings.about': 'About',
    'settings.signOut': 'Sign Out',
    'settings.darkMode': 'Dark Mode',
    'settings.notifications': 'Notifications',
    
    // Job Detail Modal
    'modal.salary.title': 'Salary',
    'modal.salary.basic': 'Basic Salary',
    'modal.salary.payment': 'Payment Method',
    'modal.salary.description': 'Hourly wage system. Raises possible based on experience and ability.',
    'modal.salary.monthlyPayment': 'Monthly payment on 25th of following month',
    'modal.salary.bankTransfer': 'Bank transfer',
    'modal.salary.transportAllowance': 'Transportation allowance provided separately',
    'modal.salary.raiseSystem': 'Raise system available',
    'modal.salary.overtimePay': 'Overtime pay available',
    
    'modal.japanese.title': 'Japanese Level',
    'modal.japanese.recommended': 'Recommended Japanese Level',
    'modal.japanese.description': 'Japanese level standard required by company',
    'modal.japanese.skills': 'Required Skills',
    'modal.japanese.dailyConversation': 'Basic daily conversation',
    'modal.japanese.workInstructions': 'Understanding work instructions',
    'modal.japanese.reporting': 'Simple reporting and communication',
    'modal.japanese.keigo': 'Basic honorific language',
    'modal.japanese.numbers': 'Numbers and time expressions',
    
    'modal.commute.title': 'Commute',
    'modal.commute.description': 'Estimated commute time from home/school to workplace. Various commute options available.',
    'modal.commute.options': 'Commute Options',
    'modal.commute.shuttleBus': 'Shuttle bus available',
    'modal.commute.bikePark': 'Bicycle parking available',
    'modal.commute.busNearby': 'Near bus stop',
    'modal.commute.trainAccess': 'Good train access',
    'modal.commute.parking': 'Parking available',
    
    'modal.location.title': 'Location',
    'modal.location.details': 'Workplace Details',
    'modal.location.access': 'Access Information',
    'modal.location.walkFromStation': '5 minutes walk from nearest station',
    'modal.location.parkingAvailable': 'Parking available',
    'modal.location.mainRoad': 'Along main road',
    'modal.location.busStop': 'In front of bus stop',
    'modal.location.surroundings': 'Surroundings',
    'modal.location.convenience': 'Near convenience store',
    'modal.location.restaurants': 'Many restaurants nearby',
    'modal.location.atm': 'Bank ATM available',
    'modal.location.hospital': 'Near hospital and pharmacy',
    
    'modal.workDays.title': 'Work Days',
    'modal.workDays.schedule': 'Working hours this store is recruiting for',
    'modal.workDays.shift1': 'Working hours ①',
    'modal.workDays.weekdays': 'Mon Tue Wed Thu Fri',
    'modal.workDays.description': 'Shift system. Adjustable through consultation.',
    
    'modal.workHours.title': 'Work Hours',
    'modal.workHours.schedule': 'Working hours this store is recruiting for',
    'modal.workHours.shift1': 'Working hours ①',
    'modal.workHours.weekdays': 'Mon Tue Wed Thu Fri',
    'modal.workHours.time': '05:00 ～ 08:00',
    'modal.workHours.description': 'Early morning shift. Those confident in physical strength welcome.',
    'modal.workHours.break': 'Break Time',
    'modal.workHours.break30': '30-minute break available',
    'modal.workHours.breakRoom': 'Break room available',
    'modal.workHours.freeDrink': 'Free drinks',
    'modal.workHours.wifi': 'WiFi available',
    
    'modal.highlights.title': 'Benefits',
    'modal.highlights.appeal': 'Workplace Appeal Points',
    'modal.highlights.description': 'Company appeal points',
    'modal.highlights.noExperience': 'No experience OK',
    'modal.highlights.other': 'Other Benefits',
    'modal.highlights.insurance': 'Social insurance provided',
    'modal.highlights.raise': 'Raises available',
    'modal.highlights.uniform': 'Uniform provided',
    'modal.highlights.training': 'Comprehensive training system',
    'modal.highlights.discount': 'Employee discount available',
    
    'modal.jobContent.title': 'Job Content',
    'modal.jobContent.description': 'Specific job duties and desired personnel',
    'modal.jobContent.mainTasks': 'Main Tasks',
    'modal.jobContent.teamwork': 'Teamwork-focused tasks',
    'modal.jobContent.safety': 'Thorough safety management',
    'modal.jobContent.quality': 'Quality control and confirmation work',
    'modal.jobContent.reporting': 'Report creation',
    'modal.jobContent.requirements': 'Desired Personnel',
    'modal.jobContent.motivated': 'Motivated individuals',
    'modal.jobContent.teamPlayer': 'Those who value teamwork',
    'modal.jobContent.responsible': 'Responsible individuals',
    'modal.jobContent.learner': 'Those with high learning motivation',
    'modal.jobContent.longTerm': 'Those who can work long-term',
  },
  uz: {
    'app.title': 'Ishlar Ro\'yxati',
    'tabs.jobs': 'Ishlar',
    'tabs.refused': 'Rad etilgan',
    'tabs.chosen': 'Tanlangan',
    'tabs.profile': 'Profil',
    'contact.title': 'Aloqa',
    'contact.phone': 'Telefon',
    'contact.email': 'Email',
    'contact.chat': 'Jonli chat',
    'contact.subtitle': 'Yordam kerakmi? Qo\'llab-quvvatlash jamoamiz bilan bog\'laning.',
    'contact.phoneDetail': 'Dush-Jum 9:00-18:00',
    'contact.emailDetail': '24 soat ichida javob',
    'contact.chatDetail': '24/7 mavjud',
    'profile.incomplete': 'Profil to\'liq emas',
    'profile.complete': 'Profilni to\'ldirish',
    'profile.edit': 'Profilni tahrirlash',
    'profile.basicInfo': 'Asosiy ma\'lumotlar',
    'profile.contactInfo': 'Aloqa ma\'lumotlari',
    'profile.workPreferences': 'Ish afzalliklari',
    'profile.firstName': 'Ism',
    'profile.lastName': 'Familiya',
    'profile.age': 'Yosh',
    'profile.gender': 'Jins',
    'profile.nationality': 'Millat',
    'profile.email': 'Email',
    'profile.phone': 'Telefon',
    'profile.japaneseLevel': 'Yapon tili darajasi',
    'profile.preferredDays': 'Afzal ko\'rilgan ish kunlari',
    'profile.preferredJobTypes': 'Afzal ko\'rilgan ish turlari',
    'profile.addPhoto': 'Rasm qo\'shish',
    'profile.save': 'Profilni saqlash',
    'profile.male': 'Erkak',
    'profile.female': 'Ayol',
    'profile.other': 'Boshqa',
    'profile.nearestStationInfo': 'Eng yaqin stansiya ma\'lumotlari',
    'profile.nearestStationHome': 'Uydan eng yaqin stansiya',
    'profile.nearestStationSchool': 'Maktabdan eng yaqin stansiya',
    'profile.walkTime': 'Piyoda vaqt (daqiqa)',
    'profile.addressInfo': 'Manzil ma\'lumotlari',
    'profile.postalCode': 'Pochta indeksi (7 xonali)',
    'profile.prefecture': 'Prefektura',
    'profile.district1': 'Shahar/tuman 1',
    'profile.district2': 'Shahar/tuman 2',
    'profile.buildingName': 'Bino nomi va xona raqami',
    'profile.residenceRights': 'Yashash huquqi',
    'profile.visaType': 'Viza turi',
    'profile.residencePhoto': 'Yashash huquqi fotosurat',
    'profile.residenceChangePlans': 'Yashash huquqini o\'zgartirish rejalari',
    'profile.certificatePhoto': 'Sertifikat fotosurat',
    'profile.otherInfo': 'Boshqa ma\'lumotlar',
    'profile.currentJob': 'Hozirgi kasbi/Talaba',
    'profile.desiredJob': 'Xohlagan kasb',
    'profile.workExperience': 'O\'tmishdagi ish tajribasi',
    'profile.selectNationality': 'Millatni tanlang',
    'profile.selectPrefecture': 'Prefekturani tanlang',
    'profile.selectVisaType': 'Viza turini tanlang',
    'profile.uploadResidenceCard': 'Yashash huquqi fotosuratini yuklang',
    'profile.uploadCertificate': 'Sertifikat fotosuratini yuklang',
    'filter.title': 'Filtr',
    'filter.jobType': 'Ish turi',
    'filter.wage': 'Maosh',
    'filter.japanese': 'Yapon tili darajasi',
    'filter.workDays': 'Ish kunlari',
    'filter.commute': 'Yo‘lda sarflanadigan vaqt',
    'filter.workPriority': 'Ishdagi ustuvorliklar',
    'filter.reset': 'Qayta o\'rnatish',
    'filter.apply': 'Filtrlarni qo\'llash',
    'sort.wage': 'Maosh bo\'yicha',
    'sort.commute': 'Yo\'l vaqti bo\'yicha',
    'sort.date': 'Sana bo\'yicha',
    'sort.title': 'Saralash',
    'empty.chosen': 'Hali tanlangan ishlar yo\'q',
    'empty.chosenSub': 'Yoqtirgan ishlaringiz shu yerda ko\'rinadi',
    'empty.refused': 'Hali rad etilgan ishlar yo\'q',
    'empty.refusedSub': 'O\'tkazib yuborilgan ishlar shu yerda ko\'rinadi',
    'language.select': 'Tilni tanlang',
    'settings.title': 'Sozlamalar',
    'settings.account': 'Hisob',
    'settings.editProfile': 'Profilni tahrirlash',
    'settings.addAccount': 'Hisob qo\'shish',
    'settings.deleteAccount': 'Hisobni o\'chirish',
    'settings.deleteAccountConfirm': 'Hisobingizni o\'chirishni xohlaysizmi? Bu amal ortga qaytarilmaydi.',
    'settings.cancel': 'Bekor qilish',
    'settings.delete': 'O\'chirish',
    'settings.preferences': 'Afzalliklar',
    'settings.support': 'Yordam',
    'settings.contact': 'Aloqa',
    'settings.about': 'Ilova haqida',
    'settings.signOut': 'Chiqish',
    'settings.darkMode': 'Qorong\'u rejim',
    'settings.notifications': 'Bildirishnomalar',
    
    // Job Detail Modal
    'modal.salary.title': 'Maosh',
    'modal.salary.basic': 'Asosiy maosh',
    'modal.salary.payment': 'To\'lov usuli',
    'modal.salary.description': 'Soatlik maosh tizimi. Tajriba va qobiliyatga qarab oshirish mumkin.',
    'modal.salary.monthlyPayment': 'Oy oxiri hisoblab keyingi oy 25-sida to\'lash',
    'modal.salary.bankTransfer': 'Bank o\'tkazmasi',
    'modal.salary.transportAllowance': 'Transport xarajatlari alohida to\'lanadi',
    'modal.salary.raiseSystem': 'Maosh oshirish tizimi mavjud',
    'modal.salary.overtimePay': 'Ortiqcha ish haqi mavjud',
    
    'modal.japanese.title': 'Yapon tili',
    'modal.japanese.recommended': 'Tavsiya etilgan yapon tili darajasi',
    'modal.japanese.description': 'Kompaniya talab qilgan yapon tili darajasi me\'yori',
    'modal.japanese.skills': 'Kerakli ko\'nikmalar',
    'modal.japanese.dailyConversation': 'Asosiy kundalik suhbat',
    'modal.japanese.workInstructions': 'Ish ko\'rsatmalarini tushunish',
    'modal.japanese.reporting': 'Oddiy hisobot va aloqa',
    'modal.japanese.keigo': 'Asosiy hurmat tili',
    'modal.japanese.numbers': 'Raqamlar va vaqt ifodalari',
    
    'modal.commute.title': 'Yo\'l vaqti',
    'modal.commute.description': 'Uydan/maktabdan ish joyigacha yo\'l vaqti taxminiy. Turli transport imkoniyatlari mavjud.',
    'modal.commute.options': 'Transport imkoniyatlari',
    'modal.commute.shuttleBus': 'Xizmat avtobusi mavjud',
    'modal.commute.bikePark': 'Velosiped to\'xtash joyi mavjud',
    'modal.commute.busNearby': 'Avtobus bekatiga yaqin',
    'modal.commute.trainAccess': 'Poyezd bilan yaxshi aloqa',
    'modal.commute.parking': 'Avtomobil to\'xtash joyi mavjud',
    
    'modal.location.title': 'Joylashuv',
    'modal.location.details': 'Ish joyi tafsilotlari',
    'modal.location.access': 'Kirish ma\'lumotlari',
    'modal.location.walkFromStation': 'Eng yaqin stansiyadan 5 daqiqa piyoda',
    'modal.location.parkingAvailable': 'To\'xtash joyi mavjud',
    'modal.location.mainRoad': 'Asosiy yo\'l bo\'ylab',
    'modal.location.busStop': 'Avtobus bekati oldida',
    'modal.location.surroundings': 'Atrofdagi muhit',
    'modal.location.convenience': 'Do\'konga yaqin',
    'modal.location.restaurants': 'Ko\'plab ovqat do\'konlari',
    'modal.location.atm': 'Bank bankomati mavjud',
    'modal.location.hospital': 'Kasalxona va dorixonaga yaqin',
    
    'modal.workDays.title': 'Ish kunlari',
    'modal.workDays.schedule': 'Bu do\'kon ishga olayotgan ish vaqtlari',
    'modal.workDays.shift1': 'Ish vaqti ①',
    'modal.workDays.weekdays': 'Dush   Sesh   Chor   Pay   Jum',
    'modal.workDays.description': 'Smena tizimi. Kelishuvga ko\'ra o\'zgartirish mumkin.',
    
    'modal.workHours.title': 'Ish vaqti',
    'modal.workHours.schedule': 'Bu do\'kon ishga olayotgan ish vaqtlari',
    'modal.workHours.shift1': 'Ish vaqti ①',
    'modal.workHours.weekdays': 'Dush   Sesh   Chor   Pay   Jum',
    'modal.workHours.time': '05:00 ～ 08:00',
    'modal.workHours.description': 'Erta tonggi smena. Jismoniy kuchga ishongan kishilar xush kelibsiz.',
    'modal.workHours.break': 'Dam olish vaqti',
    'modal.workHours.break30': '30 daqiqalik dam olish mavjud',
    'modal.workHours.breakRoom': 'Dam olish xonasi mavjud',
    'modal.workHours.freeDrink': 'Bepul ichimliklar',
    'modal.workHours.wifi': 'WiFi mavjud',
    
    'modal.highlights.title': 'Afzalliklar',
    'modal.highlights.appeal': 'Ish joyining jozibali tomonlari',
    'modal.highlights.description': 'Kompaniyaning jozibali nuqtalari',
    'modal.highlights.noExperience': 'Tajribasiz bo\'lsa ham bo\'ladi',
    'modal.highlights.other': 'Boshqa afzalliklar',
    'modal.highlights.insurance': 'Ijtimoiy sug\'urta to\'liq',
    'modal.highlights.raise': 'Maosh oshirish mavjud',
    'modal.highlights.uniform': 'Forma beriladi',
    'modal.highlights.training': 'O\'quv tizimi yaxshi',
    'modal.highlights.discount': 'Xodim chegirmasi mavjud',
    
    'modal.jobContent.title': 'Ish mazmuni',
    'modal.jobContent.description': 'Aniq ish vazifalari va kerakli xodimlar',
    'modal.jobContent.mainTasks': 'Asosiy vazifalar',
    'modal.jobContent.teamwork': 'Jamoa ishiga e\'tibor beriladigan vazifalar',
    'modal.jobContent.safety': 'Xavfsizlik nazoratining to\'liq ta\'minlanishi',
    'modal.jobContent.quality': 'Sifat nazorati va tasdiqlash ishlari',
    'modal.jobContent.reporting': 'Hisobot yaratish',
    'modal.jobContent.requirements': 'Kerakli xodimlar',
    'modal.jobContent.motivated': 'Motivatsiyali shaxslar',
    'modal.jobContent.teamPlayer': 'Jamoa ishini qadrlaydigan kishilar',
    'modal.jobContent.responsible': 'Mas\'uliyatli shaxslar',
    'modal.jobContent.learner': 'O\'rganishga ishtiyoqi yuqori kishilar',
    'modal.jobContent.longTerm': 'Uzoq muddat ishlay oladigan kishilar',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ja');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}